# Generated by Django 4.2.7 on 2023-11-11 05:26

import Employeeform.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to=Employeeform.models.unique_img_name),
        ),
    ]
